export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <body>
      <div className="min-h-screen bg-gray-100 py-8 print:bg-white print:py-0">
        <div className="mx-auto max-w-[210mm] bg-white shadow-lg print:shadow-none">
          <div className="a4-page">
            {children}
          </div>
        </div>
      </div>
    </body>
  )
}
